---
configuration_directory: "%{cwd}/examples/full"
state_file: "%{cwd}/state/full.tfstate"
vars:
  region: "%{hiera('region')}"

  role_name: "cross-account-test-role"
  policy_arn: "arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess"
  assumable_by_account_ids:
    - "176145454894"
